### PR TITLE
Exempt -RunAsAdmin requirement when run in GitHub Actions

### PR DESCRIPTION
**Pull request by sirredbeard**
Addresses issue https://github.com/ScoopInstaller/Scoop/issues/5800

### CODE REVIEW

**Review by chawyehsu — COMMENTED** [review]
There is currently already an exception for Windows Sandbox `-and $env:USERNAME -ne 'WDAGUtilityAccount'` in LOC121, it would be preferable to gather these conditions to one new line of _if statement_.

```diff
diff --git a/install.ps1 b/install.ps1
index 4e82228..00f48ae 100644
--- a/install.ps1
+++ b/install.ps1
@@ -118,7 +118,7 @@ function Test-ValidateParameter {
 function Test-IsAdministrator {
     return ([Security.Principal.WindowsPrincipal]`
             [Security.Principal.WindowsIdentity]::GetCurrent()`
-    ).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator) -and $env:USERNAME -ne 'WDAGUtilityAccount'
+    ).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
 }
 
 function Test-Prerequisite {
@@ -139,7 +139,12 @@ function Test-Prerequisite {
 
     # Detect if RunAsAdministrator, there is no need to run as administrator when installing Scoop.
     if (!$RunAsAdmin -and (Test-IsAdministrator)) {
-        Deny-Install "Running the installer as administrator is disabled by default, see https://github.com/ScoopInstaller/Install#for-admin for details."
+        # Exception: Windows Sandbox, GitHub Actions CI
+        $exception = ($env:USERNAME -eq 'WDAGUtilityAccount') -or ($env:GITHUB_ACTIONS -eq 'true' -and $env:CI -eq 'true')
+
+        if (!$exception) {
+            Deny-Install "Running the installer as administrator is disabled by default, see https://github.com/ScoopInstaller/Install#for-admin for details."
+        }
     }
```

**Comment by sirredbeard** [comment]
That would work for me. Should I push that implementation to my branch, @chawyehsu?

**Comment by chawyehsu** [comment]
yes please go ahead.

**Comment by sirredbeard** [comment]
Pushed changes.

**Pull request merged**
